-- Dạng bài mới ERROR_CORRECTION: đề là câu SAI, người học phải tự tìm lỗi và viết lại cả câu.
--
-- Vì sao thêm: 4 dạng cũ đều đã chỉ sẵn chỗ cần xử lý (___ , các phương án, các từ cần sắp xếp).
-- Người học nhận ra đúng/sai khi được trỏ vào tận nơi, nhưng lúc tự viết thì không ai trỏ cho.
-- Dạng này bắt quét cả câu, sát với lỗi thật khi viết.
--
-- Nội dung: 34 câu bám các lỗi kinh điển của người Việt học tiếng Đức (quên đuôi -est, V2,
-- Akkusativ sau haben, haben/sein ở Perfekt, weil + động từ cuối câu, quên "zu", n-Deklination...).
-- Tự soạn, không lấy câu nào từ tài liệu có bản quyền.
--
-- Lưu ý khi soạn thêm: GrammarGradingService bỏ dấu phẩy và dấu câu cuối trước khi so khớp, nên
-- KHÔNG được ra câu mà lỗi duy nhất là thiếu dấu phẩy — câu đó sẽ luôn được chấm là đúng.

INSERT INTO grammar_exercises
    (topic_id, order_index, exercise_type, prompt_de, hint_vi, correct_answer, explanation_vi,
     generated_by, reviewed)
SELECT t.id,
       COALESCE((SELECT max(e.order_index) FROM grammar_exercises e WHERE e.topic_id = t.id), 0)
           + row_number() OVER (PARTITION BY v.slug ORDER BY v.n),
       'ERROR_CORRECTION', v.prompt_de, v.hint_vi, v.correct_answer, v.explanation_vi,
       'MANUAL', true
FROM (VALUES
    -- A1
    ('a1-verb-konjugation', 1,
     'Du arbeitst im Büro.',
     'Thân động từ kết thúc bằng -t thì đuôi chia có gì khác?',
     'Du arbeitest im Büro.',
     'Thân "arbeit-" đã tận cùng bằng -t nên phải chèn -e- trước đuôi: du arbeitest. Tương tự: du findest, er antwortet.'),
    ('a1-verb-konjugation', 2,
     'Wir wohnt in Hanoi.',
     'Chủ ngữ "wir" đi với đuôi nào?',
     'Wir wohnen in Hanoi.',
     'Ngôi wir dùng đuôi -en: wir wohnen. Đuôi -t là của ihr và er/sie/es.'),

    ('a1-wortstellung-hauptsatz', 1,
     'Morgen ich gehe zum Arzt.',
     'Trong câu kể, động từ đứng ở vị trí thứ mấy?',
     'Morgen gehe ich zum Arzt.',
     'Quy tắc V2: động từ chia luôn đứng ở vị trí thứ hai. Đưa "Morgen" lên đầu thì chủ ngữ phải lùi ra sau động từ.'),
    ('a1-wortstellung-hauptsatz', 2,
     'Warum du kommst nicht?',
     'Sau từ để hỏi là thành phần nào?',
     'Warum kommst du nicht?',
     'Câu hỏi có từ để hỏi cũng theo V2: từ để hỏi - động từ - chủ ngữ.'),

    ('a1-nomen-artikel-akkusativ', 1,
     'Ich habe ein Bruder.',
     'Danh từ giống đực ở cách 4 đổi mạo từ thế nào?',
     'Ich habe einen Bruder.',
     'haben đi với Akkusativ. Giống đực ở Akkusativ: ein thành einen, der thành den. Giống cái và trung tính không đổi.'),
    ('a1-nomen-artikel-akkusativ', 2,
     'Er kauft der Tisch.',
     'Tân ngữ trực tiếp đứng ở cách mấy?',
     'Er kauft den Tisch.',
     'kaufen đi với Akkusativ, der Tisch thành den Tisch.'),

    ('a1-praeposition-dativ', 1,
     'Ich fahre mit der Bus.',
     'Giới từ "mit" luôn đi với cách nào?',
     'Ich fahre mit dem Bus.',
     'mit luôn đi với Dativ. Giống đực ở Dativ: der thành dem.'),
    ('a1-praeposition-dativ', 2,
     'Nach die Arbeit gehe ich nach Hause.',
     'Giống cái ở Dativ dùng mạo từ nào?',
     'Nach der Arbeit gehe ich nach Hause.',
     'nach cũng thuộc nhóm giới từ luôn đi Dativ. Giống cái ở Dativ: die thành der.'),

    ('a1-perfekt', 1,
     'Ich habe nach Berlin gefahren.',
     'Động từ chỉ sự di chuyển dùng trợ động từ nào?',
     'Ich bin nach Berlin gefahren.',
     'Động từ chỉ di chuyển hoặc thay đổi trạng thái (fahren, gehen, kommen, aufstehen) chia Perfekt với sein.'),
    ('a1-perfekt', 2,
     'Wir haben gestern Fußball gespielen.',
     'Partizip II của động từ yếu kết thúc bằng gì?',
     'Wir haben gestern Fußball gespielt.',
     'spielen là động từ yếu: ge- + thân + -t, thành gespielt. Đuôi -en là của động từ mạnh (gefahren, gesehen).'),

    ('a1-modalverben', 1,
     'Ich kann Deutsch spreche.',
     'Động từ thứ hai đứng cuối câu ở dạng nào?',
     'Ich kann Deutsch sprechen.',
     'Chỉ động từ khuyết thiếu được chia; động từ chính đứng cuối câu ở nguyên thể: kann ... sprechen.'),
    ('a1-modalverben', 2,
     'Wir möchten ins Kino zu gehen.',
     'Sau động từ khuyết thiếu có cần "zu" không?',
     'Wir möchten ins Kino gehen.',
     'Sau động từ khuyết thiếu là nguyên thể trần, không có zu. Chỉ các động từ như vergessen, versuchen mới cần zu.'),

    ('a1-trennbare-verben', 1,
     'Der Zug ankommt um acht Uhr.',
     'Tiền tố tách được đi đâu trong câu chính?',
     'Der Zug kommt um acht Uhr an.',
     'Động từ tách được: phần chia đứng vị trí thứ hai, tiền tố an- rơi xuống cuối câu.'),
    ('a1-trennbare-verben', 2,
     'Ich aufstehe um sechs Uhr.',
     'Phần nào của động từ được chia?',
     'Ich stehe um sechs Uhr auf.',
     'aufstehen tách thành stehe ... auf. Tiền tố luôn nằm cuối câu chính.'),

    -- A2
    ('a2-nebensatz-kausal', 1,
     'Ich bleibe zu Hause, weil ich bin krank.',
     'Trong mệnh đề phụ, động từ chia nằm ở đâu?',
     'Ich bleibe zu Hause, weil ich krank bin.',
     'weil mở mệnh đề phụ nên động từ chia bị đẩy xuống cuối: weil ich krank bin. Muốn giữ trật tự thường thì dùng denn.'),
    ('a2-nebensatz-kausal', 2,
     'Sie kommt nicht, weil sie hat keine Zeit.',
     'So sánh trật tự từ sau weil và sau denn.',
     'Sie kommt nicht, weil sie keine Zeit hat.',
     'Cùng một lỗi hay gặp: sau weil, động từ chia phải đứng cuối mệnh đề phụ.'),

    ('a2-reflexive-verben', 1,
     'Ich freue auf das Wochenende.',
     'Động từ phản thân thiếu thành phần nào?',
     'Ich freue mich auf das Wochenende.',
     'sich freuen auf bắt buộc có đại từ phản thân. Ngôi ich dùng mich.'),
    ('a2-reflexive-verben', 2,
     'Wir treffen sich am Bahnhof.',
     'Đại từ phản thân đổi theo ngôi nào?',
     'Wir treffen uns am Bahnhof.',
     'sich chỉ dùng cho ngôi thứ ba và Sie. Ngôi wir dùng uns, ngôi ihr dùng euch.'),

    ('a2-adjektivdeklination', 1,
     'Das ist ein neu Auto.',
     'Tính từ đứng trước danh từ có được để trần không?',
     'Das ist ein neues Auto.',
     'Sau mạo từ không xác định ein với danh từ trung tính, tính từ lấy đuôi -es: ein neues Auto.'),
    ('a2-adjektivdeklination', 2,
     'Sie trägt einen rot Mantel.',
     'Đuôi tính từ sau einen là gì?',
     'Sie trägt einen roten Mantel.',
     'Giống đực ở Akkusativ sau einen, tính từ lấy đuôi -en: einen roten Mantel.'),

    ('a2-wechselpraeposition', 1,
     'Ich hänge das Bild an der Wand.',
     'Câu này trả lời cho câu hỏi Wo hay Wohin?',
     'Ich hänge das Bild an die Wand.',
     'hängen ở đây là hành động có hướng (Wohin?) nên giới từ đi với Akkusativ: an die Wand.'),
    ('a2-wechselpraeposition', 2,
     'Das Buch liegt auf den Tisch.',
     'liegen mô tả vị trí hay chuyển động?',
     'Das Buch liegt auf dem Tisch.',
     'liegen chỉ vị trí đứng yên (Wo?) nên dùng Dativ: auf dem Tisch. So với legen: Ich lege das Buch auf den Tisch.'),

    -- B1
    ('b1-nebensatz-final', 1,
     'Ich spare Geld, um ein Auto kaufen.',
     'Cấu trúc um ... zu thiếu chữ gì?',
     'Ich spare Geld, um ein Auto zu kaufen.',
     'Cấu trúc um ... zu + Infinitiv luôn cần zu ngay trước động từ nguyên thể ở cuối.'),
    ('b1-nebensatz-final', 2,
     'Wir fahren mit dem Rad, um zu Geld sparen.',
     '"zu" đứng ở đâu so với động từ nguyên thể?',
     'Wir fahren mit dem Rad, um Geld zu sparen.',
     'zu đứng liền ngay trước động từ nguyên thể, và cả cụm nằm cuối mệnh đề: um Geld zu sparen.'),

    ('b1-relativsatz', 1,
     'Das ist der Mann, den mir geholfen hat.',
     'Đại từ quan hệ đóng vai trò chủ ngữ hay tân ngữ ở đây?',
     'Das ist der Mann, der mir geholfen hat.',
     'Trong mệnh đề quan hệ, đại từ làm chủ ngữ nên ở Nominativ: der. den là Akkusativ, dùng khi nó là tân ngữ trực tiếp.'),
    ('b1-relativsatz', 2,
     'Ich habe einen Freund, der ich oft helfe.',
     'helfen đi với cách nào?',
     'Ich habe einen Freund, dem ich oft helfe.',
     'Cách của đại từ quan hệ do động từ trong mệnh đề phụ quyết định. helfen đi với Dativ nên dùng dem.'),

    ('b1-passiv', 1,
     'Das Fenster wird von mir geöffnen.',
     'Partizip II của öffnen là gì?',
     'Das Fenster wird von mir geöffnet.',
     'öffnen là động từ yếu nên Partizip II là geöffnet. Bị động = werden + Partizip II.'),
    ('b1-passiv', 2,
     'Der Kuchen wird von die Mutter gebacken.',
     'Giới từ "von" đi với cách nào?',
     'Der Kuchen wird von der Mutter gebacken.',
     'Người thực hiện hành động trong câu bị động đi sau von + Dativ: von der Mutter.'),

    -- B2
    ('b2-n-deklination', 1,
     'Ich helfe dem Student.',
     'Student thuộc nhóm danh từ nào?',
     'Ich helfe dem Studenten.',
     'Student thuộc n-Deklination: mọi cách trừ Nominativ số ít đều thêm -en. Tương tự: Mensch, Kunde, Nachbar.'),
    ('b2-n-deklination', 2,
     'Der Junge spricht mit einem Kollege.',
     'Danh từ sau mit cần đuôi gì?',
     'Der Junge spricht mit einem Kollegen.',
     'Kollege cũng thuộc n-Deklination nên ở Dativ thành Kollegen.'),

    ('b2-infinitivsatz', 1,
     'Er hat vergessen, die Tür schließen.',
     'Sau vergessen cần thêm gì trước động từ nguyên thể?',
     'Er hat vergessen, die Tür zu schließen.',
     'vergessen, versuchen, versprechen... đi với mệnh đề nguyên thể có zu.'),
    ('b2-infinitivsatz', 2,
     'Ich habe vor, morgen früh zu aufstehen.',
     'Động từ tách được đặt "zu" ở đâu?',
     'Ich habe vor, morgen früh aufzustehen.',
     'Với động từ tách được, zu nằm GIỮA tiền tố và thân: aufzustehen, einzukaufen, mitzukommen.'),

    ('b2-konjunktiv-1', 1,
     'Er sagt, er hat keine Zeit.',
     'Lời nói gián tiếp trang trọng dùng thức nào?',
     'Er sagt, er habe keine Zeit.',
     'Lời nói gián tiếp (báo chí, văn viết) dùng Konjunktiv I: haben thành habe.'),
    ('b2-konjunktiv-1', 2,
     'Sie sagte, sie kommt später.',
     'Dạng Konjunktiv I của kommen ở ngôi sie số ít là gì?',
     'Sie sagte, sie komme später.',
     'Konjunktiv I lấy thân động từ + -e: sie komme, er gehe, er sehe.')
) AS v(slug, n, prompt_de, hint_vi, correct_answer, explanation_vi)
JOIN grammar_topics t ON t.slug = v.slug;
